//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApiDotNetFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Definition { get; set; }
        public string LevelOfDifficulty { get; set; }
        public bool ICanDoIt { get; set; }
        public byte[] File { get; set; }
    }
}
